language: android

android:
   components:
   - tools
   - platform-tools
   - build-tools-28.0.1
   - android-28
   - sys-img-armeabi-v7a-android-tv-l

jdk: oraclejdk8

sudo: required

before_install:
  - chmod +x gradlew

before_script:
  - ./gradlew clean assembleDebug --no-daemon --stacktrace

script:
  - ./gradlew build

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never
